## _config.yml
```yaml
title: Zachary Plato Portfolio
email: zach.plato@gmail.com
description: >-
  Portfolio site for Zachary Plato — Software and DevOps Engineer.
baseurl: "" # leave blank as you are deploying to zplato.github.io
url: "https://zplato.github.io"
theme: minima

github_username: zplato
linkedin_username: zacharyplato

plugins:
  - jekyll-feed
```
